Repository Enterprise-CMCS/cmcs-eregulations, pull requests merged in 2023-12, with the labels that each got.

#1070 updated environment value and action version
  .github/workflows/schedule-jira-sync.yml
  .github/workflows/snyk-test.yml
Labels: Approved

#1084 EREGCSC-2373 -- Policy Repository/Subject Page Header
  solution/static-assets/regulations/fonts/Merriweather-Bold.ttf
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/regulations/.eslintrc.json
  solution/ui/regulations/css/scss/_application_settings.scss
  solution/ui/regulations/css/scss/partials/_policy_repository.scss
  solution/ui/regulations/eregs-vite/src/components/policy-repository/SelectedSubjectHeading.vue
  solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectTOC.vue
  solution/ui/regulations/eregs-vite/src/views/PolicyRepository.vue
  solution/ui/regulations/package-lock.json
  solution/ui/regulations/utilities/filters.js
  solution/ui/regulations/utilities/filters.test.js
Labels: Approved

#1085 EREGCSC-2267 Sanitize filenames
  solution/backend/file_manager/admin.py
Labels: Approved

#1086 Extractor conditonal deploy
  .github/workflows/deploy-experimental.yml
  .github/workflows/remove-experimental.yml
  solution/backend/serverless-experimental.yml
Labels: Changes Requested

#1088 EREGCSC-2374 -- Alphabetize subject chips for each item
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/e2e/cypress/fixtures/policy-docs.json
  solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectChips.vue
  solution/ui/regulations/utilities/filters.js
  solution/ui/regulations/utilities/filters.test.js
Labels: Approved

#1087 EREGCSC-2356 Extract text from PowerPoint decks
  solution/text-extractor/extractors/office.py
  solution/text-extractor/extractors/tests/fixtures/pptx_expected.txt
  solution/text-extractor/extractors/tests/fixtures/pptx_sample.pptx
  solution/text-extractor/extractors/tests/test_office.py
Labels: Approved

#1083 EREGCSC-2265 Extract text from Excel sheets
  solution/text-extractor/backends/s3.py
  solution/text-extractor/backends/tests/test_backend.py
  solution/text-extractor/backends/tests/test_s3.py
  solution/text-extractor/backends/tests/test_web.py
  solution/text-extractor/extractors/__init__.py
  solution/text-extractor/extractors/office.py
  solution/text-extractor/extractors/tests/fixtures/doc_expected.txt
  solution/text-extractor/extractors/tests/fixtures/doc_sample.doc
  solution/text-extractor/extractors/tests/fixtures/docx_expected.txt
  solution/text-extractor/extractors/tests/fixtures/docx_sample.docx
  solution/text-extractor/extractors/tests/fixtures/pdf_sample.pdf
  solution/text-extractor/extractors/tests/fixtures/pptx_expected.txt
  solution/text-extractor/extractors/tests/fixtures/pptx_sample.pptx
  solution/text-extractor/extractors/tests/fixtures/xls_expected.txt
  solution/text-extractor/extractors/tests/fixtures/xls_sample.xls
  solution/text-extractor/extractors/tests/fixtures/xlsm_sample.xlsm
  solution/text-extractor/extractors/tests/fixtures/xlsx_expected.txt
  solution/text-extractor/extractors/tests/fixtures/xlsx_sample.xlsx
  solution/text-extractor/extractors/tests/test_binary.py
  solution/text-extractor/extractors/tests/test_office.py
  solution/text-extractor/extractors/tests/test_pdf.py
  solution/text-extractor/extractors/tests/test_text.py
  solution/text-extractor/extractors/text.py
  solution/text-extractor/extractors/word.py
  solution/text-extractor/text_extractor.py
Labels: Approved

#1095 EREGCSC-2265-B Add xlsm file type support
  solution/text-extractor/extractors/office.py
  solution/text-extractor/extractors/tests/fixtures/xlsm_expected.txt
  solution/text-extractor/extractors/tests/test_office.py
Labels: Approved

#1102 Eregcsc 2016 deploy eua changes prod
  solution/backend/cmcs_regulations/settings/base.py
  solution/backend/cmcs_regulations/settings/deploy.py
  solution/backend/cmcs_regulations/settings/local.py
Labels: Needs Review

#1097 EREGCSC-2418 - Modify SecurityHub Jira Sync to Generate Low-Priority Issues
  .github/workflows/schedule-jira-sync.yml
Labels: Approved

#1098 Eregcsc 2345 - Categories and subcategories for Uploaded content
  solution/backend/common/mixins.py
  solution/backend/common/serializers/clean.py
  solution/backend/common/serializers/mix.py
  solution/backend/common/utils.py
  solution/backend/content_search/functions.py
  solution/backend/content_search/migrations/0006_contentindex_upload_category.py
  solution/backend/content_search/models.py
  solution/backend/content_search/serializers.py
  solution/backend/file_manager/admin.py
  solution/backend/file_manager/migrations/0015_auto_20231207_1615.py
  solution/backend/file_manager/models.py
  solution/backend/file_manager/serializers.py
  solution/backend/file_manager/serializers/files.py
  solution/backend/file_manager/serializers/groupings.py
  solution/backend/file_manager/urls.py
  solution/backend/file_manager/views.py
  solution/backend/resources/models.py
  solution/backend/resources/serializers/categories.py
  solution/backend/resources/serializers/locations.py
  solution/backend/resources/serializers/resources.py
Labels: Approved

#1076 [Snyk] Security upgrade pillow from 9.5.0 to 10.0.1
  solution/text-extractor/requirements.txt
Labels: Approved

#1101 EREGCSC-2410 -- Adjust display of public items in policy repository
  solution/backend/content_search/models.py
  solution/backend/content_search/serializers.py
  solution/backend/content_search/tests/test_search.py
  solution/ui/regulations/.eslintrc.json
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.test.js
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
Labels: Approved

#1106 EREGCSC-2267 sanitize file names
  solution/backend/file_manager/admin.py
  solution/backend/file_manager/tests/test_admin.py
Labels: Approved

#1104 EREGCSC-2419 Documentation for processes
  README.md
  solution/Makefile
  solution/backend/regcore/search/readme.md
  solution/backend/serverless_functions/readme.md
  solution/text-extractor/README.md
Labels: Approved

#1114 EREGCSC-2345 - Admin dropdown correction for dropdown
  solution/backend/file_manager/admin.py
Labels: Needs Review

#1112 EREGCSC-2410 -- Updated snippet ellipses logic
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.test.js
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
Labels: Approved

#1115 EREGCSC-2252-B Fix attachment extraction for zip, eml, and msg files
  .github/workflows/deploy-experimental.yml
  solution/backend/serverless-experimental.yml
  solution/text-extractor/extractors/email.py
  solution/text-extractor/extractors/outlook.py
  solution/text-extractor/extractors/tests/fixtures/eml_pdf_expected.txt
  solution/text-extractor/extractors/tests/test_email.py
  solution/text-extractor/extractors/zip.py
  solution/text-extractor/text_extractor.py
Labels: Needs Review
