Repository Enterprise-CMCS/cmcs-eregulations, pull requests merged in 2023-11, with the labels that each got.

#1028 EREGCSC-2293 -- "Download X" chips on subject pages for uploaded files
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/e2e/cypress/fixtures/policy-docs.json
  solution/ui/regulations/css/scss/partials/_results_item.scss
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
  solution/ui/regulations/utilities/utils.js
  solution/ui/regulations/utilities/utils.test.js
Labels: Needs Review

#1022 EREGCSC-2327 -- Item counts on subject lookup homepage
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/e2e/cypress/fixtures/subjects.json
  solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectTOC.vue
  solution/ui/regulations/eregs-vite/src/views/PolicyRepository.vue
Labels: Needs Review

#1044 [Hotfix] Revert CMS Design System back to v2.5
  solution/ui/regulations/package.json
Labels: Merge when approved

#1047 [Hotfix] Search page resources external link style regression
  solution/ui/regulations/css/scss/partials/_search.scss
Labels: Needs Review

#1046 EREGCSC-2339 Add content search headline
  solution/backend/content_search/models.py
  solution/backend/content_search/serializers.py
  solution/backend/content_search/tests/test_search.py
Labels: Needs Review

#1054 Eregcsc 2290 edit button uploaded items
  .github/workflows/deploy-experimental.yml
  .github/workflows/deploy.yml
  solution/backend/cmcs_regulations/fixtures/auth.group.json
  solution/backend/content_search/serializers.py
  solution/backend/content_search/urls.py
  solution/backend/content_search/views.py
  solution/backend/createsu.py
  solution/backend/regulations/admin.py
  solution/backend/regulations/templates/regulations/policy_repository.html
  solution/backend/regulations/tests/test_admin.py
  solution/backend/regulations/views/policy_repository.py
  solution/backend/serverless-experimental.yml
  solution/backend/serverless.yml
  solution/ui/e2e/cypress.env.json.template
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/e2e/cypress/fixtures/policy-docs.json
  solution/ui/e2e/cypress/support/common-commands/login.js
  solution/ui/regulations/css/scss/partials/_policy_repository.scss
  solution/ui/regulations/eregs-component-lib/src/components/shared-components/ResultsItem.vue
  solution/ui/regulations/eregs-vite/src/App.vue
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
  solution/ui/regulations/eregs-vite/src/views/PolicyRepository.vue
Labels: Do Not Merge, Needs Review

#1073 EREGCSC-2370 -- Move "Filter the subject list" into input field
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/regulations/css/scss/partials/_policy_repository.scss
  solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectSelector.vue
Labels: Approved

#1074 EREGCSC-2371 -- Add Document Type labels to Policy Repo search results
  solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
  solution/ui/regulations/css/scss/partials/_results_item.scss
  solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/CategoryLabel.vue
  solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/DocTypeLabel.test.js
  solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/DocTypeLabel.vue
  solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/__snapshots__/DocTypeLabel.test.js.snap
  solution/ui/regulations/eregs-vite/src/components/policy-repository/DocumentTypeSelector.vue
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
  solution/ui/regulations/utilities/utils.js
Labels: Approved

#1072 EREGCSC-2369 -- Change repository sidebar to not be sticky
  solution/ui/regulations/css/scss/partials/_policy_repository.scss
  solution/ui/regulations/eregs-component-lib/package-lock.json
  solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicySidebar.vue
Labels: Approved

#1075 [Snyk] Security upgrade vue-loader from 15.11.1 to 16.0.0
  solution/ui/regulations/package.json
Labels: Approved
